const paths = {
    resume: '/Ena_Kohli_Resume.pdf',
    me: '/Profile_pic.jpg',
    university: '/university_logo.png',
    angular: '/angularjs.png',
    react: '/react.png',
    nodejs: '/nodejs.png',
    mongodb: '/mongodb.png',
    bash: '/bash.png',
    python: '/python.png',
    java: '/java.png',
    html: '/html.png',
    css: '/css.png',
    javascript: '/javascript.png',
    rust: '/rust.png',
    elixir: '/elixir.png',
    dotnet: '/dotnet.png',
    sql: '/sql.png',
    vba: '/vba.png',
    csharp: '/csharp.png',
    typescript: '/typescript.png',
    ttc: '/ttc.png',
    fgf: '/fgf.png',
    microsoft: '/microsoft.png',
    php: '/php.png',
    automate: '/automate.png',
    bi: '/bi.png',
    tailwind: '/tailwind.png',
}
 
export default paths;